Disable all {problems} text when settings is disabled
leonardssh/vscord pull request #128
Opened 2022-10-24 14:06 UTC by nick22985

Fixes #127 prob a better way of doing this

2022-10-24 19:15 UTC, leonardssh approved these changes

2022-10-27 02:08 UTC, xhayper commented
Just saw this, my bad!

2022-10-27 02:09 UTC, xhayper requested changes

2022-10-27 02:09 UTC, xhayper commented on src/activity.ts
> +    ) : '';
use `FAKE_EMPTY` instead of `''`

2022-10-27 04:52 UTC, merged

2022-10-27 06:20 UTC, xhayper reviewed
LGTM!

2022-10-27 06:22 UTC, xhayper commented
idk how that comment get there, ignore it