attempted to add Fortran recognition
leonardssh/vscord pull request #79
Opened 2022-07-29 21:03 UTC by CC-4477

not sure if I did this right, but I'm trying to add Fortran file recognition

2022-07-30 14:21 UTC, localip requested changes

2022-07-30 14:21 UTC, localip commented on src/data/languages.json
> +		{ "language": "fortran", "image" : "fortran"},
Could you match the spacing at the end bracket with the one on the starting one?

2022-07-30 14:21 UTC, localip commented on src/data/languages.json
> +		".f90": { "image": "fortran"},
Same with the rest down here.

2022-08-03 06:34 UTC, siyengar04 commented on src/data/languages.json
> +		{ "language": "fortran", "image" : "fortran"},
done

2022-08-03 06:34 UTC, siyengar04 commented on src/data/languages.json
> +		".f90": { "image": "fortran"},
and done!

2022-10-16 05:46 UTC, xhayper commented
I personally don't think the icon fits, because the purple background + transparent background

2022-10-22 15:24 UTC, closed without merging